name: 'SQL Linting'
description: 'Run SQLFluff to lint SQL files'

inputs:
  directory:
    description: 'Directory containing SQL files to lint'
    required: true
    default: 'dir/'

  language:
    description: 'Programing language to lint. Possible choice are: SQL, Python'
    required: true

  dialect:
    description: 'SQL dialect to use for linting'
    required: false

  config:
    description: 'Path to SQLFluff configuration file'
    required: false

  stop_on_fail:
    description: 'Stop workflow on linting failure'
    required: true
    default: 'true'

outputs:
  output:
    description: 'Output from SQLFluff'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Validate Language Input
      run: |
        language="${{ inputs.language }}"
        if [[ "$language" != "SQL" && "$language" != "Python" ]]; then
            echo "Error: Unsupported language $language. Only 'SQL' or 'Python' are allowed."
            exit 1
        fi
      shell: bash

    - name: Setup Environment
      run: echo "Setting up for ${{ inputs.language }}"
      shell: bash

    - name: Lint SQL
      if: ${{ inputs.language == 'SQL' }}
      run: |
        echo "Linting SQL with dialect ${{ inputs.dialect || 'default' }}"
        pip install sqlfluff==3.0.1
        sqlfluff lint ${{ inputs.directory }} --dialect ${{ inputs.dialect }} --config ${{ inputs.config }}
        SQLFLUFF_EXIT_CODE=$?
        if [ "$SQLFLUFF_EXIT_CODE" != "0" ]; then
          echo "SQLFluff found issues."
          echo ${{ inputs.stop_on_fail }}
          if [ ${{ inputs.stop_on_fail }} == true ]; then
            exit 1
          fi
        fi
      shell: bash

    - name: Lint Python
      if: ${{ inputs.language == 'Python' }}
      run: |
        echo "Linting Python"
        pip install flake8==7.0.0
        python -m flake8 ${{ inputs.directory }}
        FLAKE8_EXIT_CODE=$?
        echo $FLAKE8_EXIT_CODE
        if [ "$FLAKE8_EXIT_CODE" != "0" ]; then
          echo "Flake8 found issues."
          echo ${{ inputs.stop_on_fail }}
          if [ ${{ inputs.stop_on_fail }} == true ]; then
            exit 1
          fi
        fi
      shell: bash
