name: 'SQL Linting'
description: 'Run SQLFluff to lint SQL files'

inputs:
  directory:
    description: 'Directory containing SQL files to lint'
    required: true
    default: 'dir/'
  dialect:
    description: 'SQL dialect to use for linting'
    required: true
    default: 'ansi'
  config:
    description: 'Path to SQLFluff configuration file'
    required: false
outputs:
  output:
    description: 'Output from SQLFluff'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install SQLFluff
      run: pip install sqlfluff

    - name: Lint SQL Files
      run: sqlfluff lint --dialect ${{ inputs.dialect }} --config ${{ inputs.config }} ${{ inputs.directory }}
      shell: bash
